[workspace]
members = [
    "ferrite",
    "ferrite-core",
    "ferrite-config",
    "ferrite-cli",
    "ferrite-logging",
    "ferrite-cache",
    "ferrite-image",
]
resolver = "2"

[workspace.package]
version = "0.1.11"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/master-of-zen/ferrite"
authors = ["master_of_zen master_of_zen@protonmail.com"]
documentation = "https://docs.rs/ferrite"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
config = { version = "0.14.1", features = ["toml"] }
directories = "5.0"
eframe = "0.26.0"
egui = "0.26.0"
futures = "0.3"
image = "0.24.8"
lru = "0.12"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tracy = "0.10"
tracy-client = "0.16"
tokio = { version = "1", features = ["full"] }
